### ISSUE TITLE
Implement Query History

### ISSUE THREAD

**Issue by agrasso-azumo** [webtimemachine/wtm2#100]
As a user , I want the ability to view and manage a history of past queries made using the LLM integration.

Acceptance Criteria:

The browser history product should record and display a history of user queries made using the LLM integration.

Each query entry in the history should include the query text, timestamp, and any relevant metadata.

Users should be able to access their query history from within the browser history interface.

The query history should support filtering and searching functionality for ease of navigation.

The history should be persistent across sessions, ensuring users can access past queries even after logging out and logging back in.

**Comment by christian-herrera-azumo** [comment]
Updated extension style for rendering history and query entries


![Image](https://github.com/webtimemachine/wtm2/assets/140095738/b8f46115-2a70-42b2-9294-690ea9831f55)



![Image](https://github.com/webtimemachine/wtm2/assets/140095738/ebca467f-ce93-40e6-af88-da9a372d05e6)

**Comment by christian-herrera-azumo** [comment]
Final UI design

![Image](https://github.com/webtimemachine/wtm2/assets/140095738/afd34729-8107-4c66-b49f-9d9b5fdec02d)

![Image](https://github.com/webtimemachine/wtm2/assets/140095738/64435d4a-934d-42e4-ac44-83cef1aa8b1d)

**Comment by christian-herrera-azumo** [comment]
PR: #132
