### ISSUE TITLE
Automatic Filtering of Explicit Content in Browsing History

### ISSUE THREAD

**Issue by agrasso-azumo** [webtimemachine/wtm2#101]
Details:
As a user, I want the browsing history feature in the LLM system to automatically filter out explicit content, ensuring a safe and appropriate browsing experience.

Acceptance Criteria:

The LLM system should employ a filtering mechanism to identify and exclude explicit content from the browsing history.

The filtering mechanism should be robust and efficient, capable of accurately detecting explicit content.

Any explicit content identified should be excluded from the browsing history records displayed to the user.

The filtering process should not significantly impact the performance or speed of browsing history retrieval.

**Comment by christian-herrera-azumo** [comment]
Added explicit content filter service

**Comment by christian-herrera-azumo** [comment]
I created this branch based on [feature/semantic-search](https://github.com/webtimemachine/wtm2/tree/feature/semantic-search)

**Comment by christian-herrera-azumo** [comment]
PR: #111
