### ISSUE TITLE
Enhanced browsing in chrome store

### ISSUE THREAD

**Issue by posix4e** [webtimemachine/wtm2#151]

**Comment by jmartel07** [comment]
It will take a few months to be considered as a trusted developer.

Link: https://support.google.com/chrome_webstore/answer/2664769?visit_id=638431154554655005-3050817726&rd=2#10745467&zippy=%2Cinstall-with-enhanced-safe-browsing:~:text=For%20new%20developers%2C%20it%20generally%20takes%20a%20few%20months%20to%20become%20trusted.%20Eventually%2C%20we%20strive%20for%20all%20developers%20with%20compliant%20extensions%20to%20reach%20this%20status%20upon%20meeting%20our%20developer%20program%20policies.
