### ISSUE TITLE
Test cronitor alert

### ISSUE THREAD

**Issue by posix4e** [webtimemachine/wtm2#157]
- break database but keep api up, does alert work
-  break http keep database up, what does alert look like

**Comment by bcarpintero-intermediait** [comment]
Cronitor alerts when API is broken

![image](https://github.com/webtimemachine/wtm2/assets/88394108/4582c4b8-68b7-43d0-803f-c0a96ce01b0e)
![image](https://github.com/webtimemachine/wtm2/assets/88394108/7b39294b-e182-422a-8819-5d0088db1954)
![image](https://github.com/webtimemachine/wtm2/assets/88394108/8ddd89c0-9aa2-4879-821a-361a34784437)
![image](https://github.com/webtimemachine/wtm2/assets/88394108/1bb0fae1-b42b-4539-b6ec-4ba377b57234)
![image](https://github.com/webtimemachine/wtm2/assets/88394108/507b1ac9-06d9-42c3-9f9b-737ed3f6e891)
![image](https://github.com/webtimemachine/wtm2/assets/88394108/8bc13383-7363-48d3-9c50-42ebdab1010b)
![image](https://github.com/webtimemachine/wtm2/assets/88394108/44a0a1f5-fb5b-485d-b163-d558d849c770)

**Comment by bcarpintero-intermediait** [comment]
Cronitor alerts when API -> DB connection is broken 

![image](https://github.com/webtimemachine/wtm2/assets/88394108/70ed0e92-a5ca-49ee-be21-c32736a6647c)
![image](https://github.com/webtimemachine/wtm2/assets/88394108/b82097fe-155a-4032-92fb-b2c198be1e97)
![image](https://github.com/webtimemachine/wtm2/assets/88394108/3477be97-60ea-4af7-8870-99a2a2d3bc1b)
![image](https://github.com/webtimemachine/wtm2/assets/88394108/bd565f37-a831-4721-80a1-f01c85102273)
![image](https://github.com/webtimemachine/wtm2/assets/88394108/e420e688-09f8-424a-9794-d72ba81321ed)

**Comment by bcarpintero-intermediait** [comment]
Hey @posix4e let me know if the Cronitor integration looks good, if so we could close this issue
