### ISSUE TITLE
[BED] Discovery on move content to kv store or simliar out of database

### ISSUE THREAD

**Issue by bcarpintero-intermediait** [webtimemachine/wtm2#169]

**Comment by bcarpintero-intermediait** [comment]
## Discovery Result

We are currently storing web page content in the PostgreSQL database in the NavigationEntry table. This approach has led to limitations such as hitting max quotas on reads, writes, and space used in our Vercel Postgres deployment.
Currently web page content is not being used in our application as we transform the content into embeddings and save it in the WeaviateStore database to be used later by the LLM search feature.

Because of this we recommend not saving this information at all, given that it is not being actively used in our application. This approach will simplify our architecture and reduce unnecessary database load.

However, if you decide that we should retain this information in case we need it in the future, we can implement an integration with a storage solution. Here are the options for storing the web page content:

### Vercel KV:

- A serverless key-value storage solution built on top of Redis.
- Integration requires using the Vercel KV SDK.
- This option may limit flexibility for end users deploying the code on their own infrastructure since  we will be coupling the implementation of this storage solution to the Vercel KV technology restricting the possibilities of the end users.

### kvstore.io:

- A cloud-based key-value storage service accessible via a REST API.
- Like Vercel KV, this option may limit end users' flexibility due to dependency on a specific third-party service.

### MongoDB:

- Integrating with MongoDB would allow end users to deploy the solution on their own infrastructure without being tied to a specific provider.
- Given that this is an open-source project intended for users to deploy on their own infrastructure, the first two options might introduce restrictions and limit their possibilities. Therefore, we recommend opting for MongoDB as it offers the best balance between flexibility and ease of deployment for end users.

As a conclusion, we think is best to not store the webpage content at all since we are not actively using this data on our application and because of the LLM implementation we are already saving the webpage content embeddings on the vector database. But if needed to save it we should use a mongo db database, integrated with the nest js application through the mongo and mongoose packages and having a service mongoService that wraps the usage of this db. Also if we decide to go on this route, we could implement this solution in a way in which the mongodb environmental variables are not required and then the mongoService only saves and reads values is the connection is available and running, making the storage of the webpage content optional for the end user.

@posix4e please let us know how you would like us to proceed based on these options.

**Comment by posix4e** [comment]
Yep let’s not store it

**Comment by posix4e** [comment]
In addition we should have a lite mode where we don’t store the embedding even

**Comment by bcarpintero-intermediait** [comment]
Hey @posix4e and which other behaviours/features should happend when lite mode is enabled?
