### ISSUE TITLE
Search Images Set Up

### ISSUE THREAD

**Issue by agrasso-azumo** [webtimemachine/wtm2#231]
We need to introduce an image captioning service/utility to extract text embeddings from images. This enhancement will allow advanced queries to include "images" in their search, leveraging their text embeddings

Now, we will be using OpenAI's multimodal models

**Comment by christian-herrera-azumo** [comment]
Added image captioning utility

**Comment by christian-herrera-azumo** [comment]
Updated extension and integrated the index process with the captioning utility

**Comment by christian-herrera-azumo** [comment]
PR: #224 @agrasso-azumo @bcarpintero-intermediait @jmartel07

**Comment by christian-herrera-azumo** [comment]
Adding user preference for enabling/disabling image captioning
