### ISSUE TITLE
Create a video of installing your own backend and using it

### ISSUE THREAD

**Issue by posix4e** [webtimemachine/wtm2#246]

**Comment by bcarpintero-intermediait** [comment]
Hey @posix4e down below I left you attached the installation video

Backed Installation Walkthrough Video:
- https://drive.google.com/file/d/1b2Zpt2pODXvnfzTl3NqUkFNTxM2U-it-/view?usp=drive_link

**Comment by posix4e** [comment]
Let’s put it on the read me, also make a moving gif

**Comment by bcarpintero-intermediait** [comment]
Hey @posix4e the [Installation Walkthrough Video](https://www.youtube.com/watch?v=sGA4V-fGf4I) follows the step by step needed to run the project on a local environment. It's a 4 min video, how do you imagine a moving gif?

**Comment by posix4e** [comment]
Ah for installation walkthrough you want snippet moving gifs to go along
with the guide . We should have a docs guy who can do it
