### ISSUE TITLE
Page Snippet

### ISSUE THREAD

**Issue by posix4e** [webtimemachine/wtm2#253]
Include a bit of text from the page on why we matched it.

WHen the user does an AI search You can just ask the LLM to quote the best matching sentence from the source

In fact you can have LLM do reranking at same time - for each source doc in prompt, output best matching sentence and doc score, then rerank by doc score

**Comment by christian-herrera-azumo** [comment]
Added support for showing the most relevant match


![Image](https://github.com/webtimemachine/wtm2/assets/140095738/43454e57-1661-4990-b5ec-24e64df64c33)

PR: #265
