### ISSUE TITLE
[FEAT]: Use tsvector along with vector for search

### ISSUE THREAD

**Issue by posix4e** [webtimemachine/wtm2#328]
We are looking for new developers to work on webtm. This is a good test project to find new people

### Description

https://neon.tech/docs/data-types/tsvector allows for full tech search directly in postgresql. This greatly reduces the amount of components needed for search and can improve performance.

### Additional Information

1) Compare and contrast the quality and cost of tsvector vs our existing solution, report on discord and let us discuss if it's any good start to develope it
2) Once you have done this begin the patch. Make sure to provide docs and tests that run in CI/CD
3) Don't worry about migration, for production we can just dump the existing databases and do it from scratch

**Comment by philippemnoel** [comment]
You should check out @paradedb, which offers better FTS than Postgres' regular FTS :)
