### ISSUE TITLE
Create status page

### ISSUE THREAD

**Issue by jmartel07** [webtimemachine/wtm2#37]
We need a status page. I like Cronitor . Create a new crontior account under the hacker plan

**Comment by bcarpintero-intermediait** [comment]
We will create an status page on Cronitor with cheacks for the Webpage (as per requested on https://github.com/webtimemachine/wtm2/issues/158) and also the Backend

**Comment by bcarpintero-intermediait** [comment]
@posix4e when you have time, please review the Cronitor page ⬆️ and let us know if its ok. 
I will be testing the assets and leaving screenshots of their working on https://github.com/webtimemachine/wtm2/issues/157
