### ISSUE TITLE
Improve logger implementation to not forward 400's https errors to discord

### ISSUE THREAD

**Issue by bcarpintero-intermediait** [webtimemachine/wtm2#663]

**Comment by posix4e** [comment]
Then how would we know what 400s are happening?

**Comment by bcarpintero-intermediait** [comment]
> Then how would we know what 400s are happening?

We can still see those erros on the vercel logs, but we think that is better not to have them on discord since they correspond to user errors (like trying to login with an incorrect password). These requests that ends up being resolved as 400's are being implemented as errors thay we throw on code (bacause of the backend framework) but they are not acctually indicators that backend is malfunctioning
