### ISSUE TITLE
Integrate LLM Query Functionality into Browser History

### ISSUE THREAD

**Issue by agrasso-azumo** [webtimemachine/wtm2#99]
Details:
As a user , I want to integrate LLM query functionality so that I can leverage advanced language processing capabilities for querying historical data.

Acceptance Criteria:

The browser history product should integrate OpenAI's LLM for query processing.

Users should be able to formulate queries using natural language within the browser history interface.

The LLM integration should accurately interpret user queries and provide relevant results based on historical data from browser history.

Results provided by LLM should be displayed seamlessly within the browser history interface, by bringing all URL that answer the query.

The integration should be efficient and not significantly impact the performance of the browser history product.

**Comment by christian-herrera-azumo** [comment]
I believe that there is no need for an LLM-based approach for enhanced searches based on site content. A semantic search approach will do

**Comment by christian-herrera-azumo** [comment]
PR: #103

**Comment by christian-herrera-azumo** [comment]
- Fixed conflicts
- Added support for chunk deletion
